/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Tag from 'components/Tag/Tag';

const TagsTablet1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `200px`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Frame2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `32px`,
  margin: `0px`,
});

const Tag1 = styled(Tag)(({ theme }) => ({
  margin: `0px`,
}));

const Tag2 = styled(Tag)(({ theme }) => ({
  margin: `0px 0px 0px 10px`,
}));

const Frame21 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `32px`,
  margin: `10px 0px 0px 0px`,
});

const Tag3 = styled(Tag)(({ theme }) => ({
  margin: `0px`,
}));

const Tag4 = styled(Tag)(({ theme }) => ({
  margin: `0px 0px 0px 10px`,
}));

const Frame5 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `32px`,
  margin: `10px 0px 0px 0px`,
});

const Tag5 = styled(Tag)(({ theme }) => ({
  margin: `0px 0px 0px 10px`,
}));

const Tag6 = styled(Tag)(({ theme }) => ({
  margin: `0px`,
}));

const Tag7 = styled(Tag)(({ theme }) => ({
  margin: `0px 0px 0px 10px`,
}));

const Frame4 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `10px 0px 0px 0px`,
});

const Tag8 = styled(Tag)(({ theme }) => ({
  margin: `0px`,
}));

const Tag9 = styled(Tag)(({ theme }) => ({
  margin: `0px 0px 0px 10px`,
}));

const Frame22 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `32px`,
  margin: `10px 0px 0px 0px`,
});

const Tag10 = styled(Tag)(({ theme }) => ({
  margin: `0px 0px 0px 10px`,
}));

const Tag11 = styled(Tag)(({ theme }) => ({
  margin: `0px`,
}));

const Tag12 = styled(Tag)(({ theme }) => ({
  margin: `0px 0px 0px 10px`,
}));

const Frame23 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `32px`,
  margin: `10px 0px 0px 0px`,
});

const Tag13 = styled(Tag)(({ theme }) => ({
  margin: `0px 0px 0px 10px`,
}));

const Tag14 = styled(Tag)(({ theme }) => ({
  margin: `0px`,
}));

const Tag15 = styled(Tag)(({ theme }) => ({
  margin: `0px 0px 0px 10px`,
}));

const Frame3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `32px`,
  margin: `10px 0px 0px 0px`,
});

const Tag16 = styled(Tag)(({ theme }) => ({
  margin: `0px`,
}));

function TagsTablet(props) {
  return (
    <TagsTablet1 className={props.className}>
      <Frame2>
        <Tag1 badgeText={'After Effect'} />
        <Tag2 badgeText={'Figma'} />
      </Frame2>
      <Frame21>
        <Tag3 badgeText={'Adobe Premiere'} />
        {false && <Tag4 />}
      </Frame21>
      <Frame5>
        {false && <Tag5 />}
        <Tag6 badgeText={'Photoshop'} />
        <Tag7 badgeText={'Midjourney'} />
      </Frame5>
      {false && (
        <Frame4>
          <Tag8 />
          <Tag9 />
        </Frame4>
      )}
      <Frame22>
        {false && <Tag10 />}
        <Tag11 badgeText={'Cinema 4D'} />
        <Tag12 badgeText={'Adobe XD'} />
      </Frame22>
      <Frame23>
        {false && <Tag13 />}
        <Tag14 badgeText={'Spline'} />
        <Tag15 badgeText={'Quest'} />
      </Frame23>
      {false && (
        <Frame3>
          <Tag16 />
        </Frame3>
      )}
    </TagsTablet1>
  );
}

export default TagsTablet;
