/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import useFormResponsiveSize from './useFormResponsiveSize';

//These are the possible values for the current variant. Use this to change the currentVariant dynamically.
//Please don't modify
const variantOptions = {
  Desktoplarg2k: 'Desktoplarg2k',
  Screendesktop1080: 'Screendesktop1080',
  ScreenTablet1024: 'ScreenTablet1024',
  Screensmalldesktop720: 'Screensmalldesktop720',
  ScreenMobile390: 'ScreenMobile390',
  Screenmobile375: 'Screenmobile375',
};

const useForm = (props) => {
  const [currentVariant, setCurrentVariant] = React.useState(
    variantOptions['Desktoplarg2k']
  );

  const breakpointsVariant = useFormResponsiveSize();

  React.useEffect(() => {
    if (breakpointsVariant !== currentVariant) {
      setCurrentVariant(breakpointsVariant);
    }
  }, [breakpointsVariant]);

  const data = { currentVariant };

  const fns = { setCurrentVariant };
  return { data, fns };
};

export default useForm;
