/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { animated, useSpring, easings } from 'react-spring';

const MenuClose = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const MenuClose1 = animated(
  styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px`,
  })
);

const MenuIco1 = styled('img')({
  height: `26px`,
  width: `26px`,
  objectFit: `cover`,
  margin: `0px`,
});

const MenuOpen = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `26px`,
  height: `26px`,
  margin: `0px 0px 0px 10px`,
});

const Close1 = styled('img')({
  height: `20px`,
  width: `20px`,
  objectFit: `cover`,
  margin: `0px`,
});

function MenuBottom(props) {
  const [MenuClose1Spring, MenuClose1Api] = useSpring(() => ({
    config: {
      duration: 500,
      easing: easings['easeOutCubic'],
    },
    delay: 100,
    from: { transform: 'rotate(0deg)', opacity: 1 },
  }));
  return (
    <MenuClose className={props.className}>
      <MenuClose1 style={{ ...MenuClose1Spring }}>
        <MenuIco1
          onClick={() => {
            MenuClose1Api.start({
              ...{ transform: 'rotate(-90deg)', opacity: 0 },
              delay: 100,
            });
          }}
          src={`assets/images/menubottom_menu_ico_1.png`}
          loading="lazy"
          alt={'menu-ico 1'}
        />
      </MenuClose1>
      {false && (
        <MenuOpen>
          <Close1
            src={`assets/images/menubottom_Close_1.png`}
            loading="lazy"
            alt={'Close 1'}
          />
        </MenuOpen>
      )}
    </MenuClose>
  );
}

export default MenuBottom;
