/**********************************************************************
 *
 *   Responsiveness hook generated by Quest
 *
 *   Responsive Logic for the component goes in this hook
 *   If you want to customize the min/max values for the breakpoints, open the component on Quest Editor.
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';

const useIndexResponsiveSize = () => {
  const [variant, setVariant] = React.useState('IndexDesktop1080');

  React.useEffect(() => {
    const handlerIndexmobile375 = (e) =>
      setVariant((size) => (e.matches ? 'Indexmobile375' : size));

    const Indexmobile375Size = window.matchMedia('(max-width: 383px)');
    setVariant((size) =>
      Indexmobile375Size.matches ? 'Indexmobile375' : size
    );
    Indexmobile375Size.addEventListener('change', handlerIndexmobile375);

    const handlerIndexMobile390 = (e) =>
      setVariant((size) => (e.matches ? 'IndexMobile390' : size));

    const IndexMobile390Size = window.matchMedia(
      '(min-width: 384px) and (max-width: 555px)'
    );
    setVariant((size) =>
      IndexMobile390Size.matches ? 'IndexMobile390' : size
    );
    IndexMobile390Size.addEventListener('change', handlerIndexMobile390);

    const handlerIndextablet720 = (e) =>
      setVariant((size) => (e.matches ? 'Indextablet720' : size));

    const Indextablet720Size = window.matchMedia(
      '(min-width: 556px) and (max-width: 872px)'
    );
    setVariant((size) =>
      Indextablet720Size.matches ? 'Indextablet720' : size
    );
    Indextablet720Size.addEventListener('change', handlerIndextablet720);

    const handlerIndextablet1024 = (e) =>
      setVariant((size) => (e.matches ? 'Indextablet1024' : size));

    const Indextablet1024Size = window.matchMedia(
      '(min-width: 873px) and (max-width: 1472px)'
    );
    setVariant((size) =>
      Indextablet1024Size.matches ? 'Indextablet1024' : size
    );
    Indextablet1024Size.addEventListener('change', handlerIndextablet1024);

    const handlerIndexDesktop1080 = (e) =>
      setVariant((size) => (e.matches ? 'IndexDesktop1080' : size));

    const IndexDesktop1080Size = window.matchMedia('(min-width: 1473px)');
    setVariant((size) =>
      IndexDesktop1080Size.matches ? 'IndexDesktop1080' : size
    );
    IndexDesktop1080Size.addEventListener('change', handlerIndexDesktop1080);
  }, []);

  return variant;
};

export default useIndexResponsiveSize;
