/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import useIndexResponsiveSize from './useIndexResponsiveSize';

//These are the possible values for the current variant. Use this to change the currentVariant dynamically.
//Please don't modify
const variantOptions = {
  IndexDesktop1080: 'IndexDesktop1080',
  Indextablet1024: 'Indextablet1024',
  Indextablet720: 'Indextablet720',
  IndexMobile390: 'IndexMobile390',
  Indexmobile375: 'Indexmobile375',
};

const useIndex = () => {
  const [currentVariant, setCurrentVariant] = React.useState(
    variantOptions['IndexDesktop1080']
  );

  const breakpointsVariant = useIndexResponsiveSize();

  React.useEffect(() => {
    if (breakpointsVariant !== currentVariant) {
      setCurrentVariant(breakpointsVariant);
    }
  }, [breakpointsVariant]);

  const data = { currentVariant };

  const fns = { setCurrentVariant };
  return { data, fns };
};

export default useIndex;
